from __future__ import annotations

import html
import re
from dataclasses import dataclass
from pathlib import Path

from agentlantern.core.base import BaseProject
from agentlantern.frameworks.registry import detect_framework

DOC_FILES = {
    "index.html",
    "_sidebar.md",
    "overview.md",
    "architecture.md",
    "agents.md",
    "tasks.md",
    "tools.md",
    "workflows.md",
    "diagrams.md",
    "contact.md",
    "runbook.md",
    "agentlantern-docs.html",
}

LEGACY_DOC_FILES = {
    "README.md",
    "index.md",
    "agent-architecture.md",
    "workflow.md",
    "configuration.md",
    "quality-report.md",
    "ownership.md",
    "glossary.md",
    "project-files.md",
}


@dataclass(frozen=True)
class DocsResult:
    project_name: str
    framework: str
    output_dir: Path
    files: list[Path]


def generate_docs(project_root: Path, output_dir: Path | None = None) -> DocsResult:
    root = project_root.resolve()
    analyzer = detect_framework(root)
    project = analyzer.analyze(root)
    renderer = analyzer.get_renderer()

    docs_dir = output_dir.resolve() if output_dir else root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    _remove_stale_agentlantern_docs(docs_dir)

    structure = renderer.get_doc_structure(project)
    markdown_files = dict(structure)
    files = {
        **markdown_files,
        "index.html": render_docsify_index(project),
        "_sidebar.md": renderer.render_sidebar(structure),
        "agentlantern-docs.html": render_share_html(project, markdown_files),
    }

    written_files: list[Path] = []
    for filename, content in files.items():
        path = docs_dir / filename
        path.write_text(content.rstrip() + "\n", encoding="utf-8")
        written_files.append(path)

    return DocsResult(
        project_name=project.name,
        framework=project.framework,
        output_dir=docs_dir,
        files=written_files,
    )


def render_docsify_index(project: BaseProject) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AgentLantern Docs - {html.escape(project.name)}</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="AgentLantern documentation for {html.escape(project.name)}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
  <style>
    :root {{
      --theme-color: #2563eb;
    }}
    .sidebar-nav strong {{
      color: #111827;
    }}
    .markdown-section {{
      max-width: 1080px;
    }}
    .markdown-section table {{
      display: table;
      width: 100%;
    }}
    .markdown-section code {{
      border-radius: 5px;
    }}
    .app-footer {{
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 13px;
    }}
  </style>
</head>
<body>
  <div id="app">Loading AgentLantern docs...</div>
  <script>
    window.$docsify = {{
      name: 'AgentLantern',
      repo: '',
      homepage: 'overview.md',
      loadSidebar: true,
      coverpage: false,
      subMaxLevel: 2,
      auto2top: true,
      search: {{
        maxAge: 86400000,
        paths: 'auto',
        placeholder: 'Search docs',
        noData: 'No results'
      }},
      mermaidConfig: {{
        querySelector: ".mermaid"
      }},
      plugins: [
        function(hook) {{
          hook.afterEach(function(html, next) {{
            next(html + '<footer class="app-footer">Generated by <a href="https://github.com/brellsanwouo/agentlantern" target="_blank" rel="noopener">AgentLantern</a> ({html.escape(project.framework)}). Powered by <a href="https://docsify.js.org/" target="_blank" rel="noopener">Docsify</a>.</footer>');
          }});
        }}
      ]
    }};
  </script>
  <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify-mermaid@2/dist/docsify-mermaid.js"></script>
</body>
</html>"""


def render_docsify_sidebar() -> str:
    return "\n".join([
        "- **[AgentLantern](https://github.com/brellsanwouo/agentlantern)**",
        "  - [Overview](overview.md)",
        "  - [Architecture](architecture.md)",
        "  - [Diagrams](diagrams.md)",
        "  - [Agents](agents.md)",
        "  - [Tasks](tasks.md)",
        "  - [Runbook](runbook.md)",
        "  - [**Contact**](contact.md)",
        "",
    ])


def render_share_html(project: BaseProject, markdown_files: dict[str, str]) -> str:
    nav = "\n".join(
        f'<a href="#{_slug(filename)}">{html.escape(_doc_title(filename))}</a>'
        for filename in markdown_files
    )
    sections = "\n".join(
        f'<section id="{_slug(filename)}">{_markdown_to_html(content)}</section>'
        for filename, content in markdown_files.items()
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AgentLantern Docs - {html.escape(project.name)}</title>
  <style>
    body {{ margin: 0; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #17202c; background: #f6f7f9; }}
    .layout {{ display: grid; grid-template-columns: 260px minmax(0, 1fr); min-height: 100vh; }}
    aside {{ position: sticky; top: 0; height: 100vh; padding: 22px 18px; background: #111827; color: white; overflow: auto; }}
    aside h1 {{ margin: 0 0 6px; font-size: 18px; }}
    aside p {{ margin: 0 0 22px; color: #bcc6d6; font-size: 13px; word-break: break-word; }}
    aside a {{ display: block; padding: 9px 10px; margin: 2px 0; border-radius: 6px; color: #e5e7eb; text-decoration: none; font-size: 14px; }}
    aside a:hover {{ background: rgba(255,255,255,.1); }}
    main {{ padding: 28px; }}
    section {{ max-width: 1040px; margin: 0 auto 24px; padding: 28px; background: white; border: 1px solid #dbe1ea; border-radius: 8px; }}
    h1 {{ margin-top: 0; }}
    h2 {{ margin-top: 30px; padding-top: 16px; border-top: 1px solid #e4e8f0; }}
    p, li {{ line-height: 1.65; }}
    code {{ padding: 1px 5px; border: 1px solid #dfe5ee; border-radius: 5px; background: #f2f4f8; }}
    pre {{ overflow: auto; padding: 16px; border-radius: 8px; background: #0f172a; color: #e5e7eb; }}
    pre code {{ border: 0; background: transparent; color: inherit; padding: 0; }}
    .mermaid {{ margin: 16px 0; padding: 18px; border: 1px solid #dbe1ea; border-radius: 8px; background: white; overflow: auto; }}
    table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }}
    th, td {{ border: 1px solid #dbe1ea; padding: 10px 12px; text-align: left; vertical-align: top; }}
    th {{ background: #f5f7fb; }}
    @media (max-width: 800px) {{ .layout {{ grid-template-columns: 1fr; }} aside {{ position: static; height: auto; }} main {{ padding: 16px; }} section {{ padding: 20px; }} }}
  </style>
</head>
<body>
  <div class="layout">
    <aside>
      <h1>AgentLantern</h1>
      <p>{html.escape(project.name)} · {html.escape(project.framework)}</p>
      <nav>{nav}</nav>
    </aside>
    <main>{sections}</main>
  </div>
  <script type="module">
    import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs";
    mermaid.initialize({{ startOnLoad: true, securityLevel: "loose" }});
  </script>
</body>
</html>"""


def _remove_stale_agentlantern_docs(docs_dir: Path) -> None:
    for filename in DOC_FILES | LEGACY_DOC_FILES | {"_coverpage.md"}:
        path = docs_dir / filename
        if path.exists():
            path.unlink()


def _doc_title(filename: str) -> str:
    return filename.removesuffix(".md").replace("-", " ").replace("_", " ").title()


def _slug(filename: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", filename.lower()).strip("-")


def _markdown_to_html(markdown: str) -> str:
    lines = markdown.splitlines()
    html_lines: list[str] = []
    table_lines: list[str] = []
    list_open = False
    code_open = False
    code_language = ""
    code_buffer: list[str] = []

    def close_list() -> None:
        nonlocal list_open
        if list_open:
            html_lines.append("</ul>")
            list_open = False

    def flush_table() -> None:
        nonlocal table_lines
        if table_lines:
            html_lines.append(_render_html_table(table_lines))
            table_lines = []

    for line in lines:
        if line.startswith("```"):
            if code_open:
                escaped = html.escape("\n".join(code_buffer))
                if code_language == "mermaid":
                    html_lines.append(f'<div class="mermaid">{escaped}</div>')
                else:
                    html_lines.append(f"<pre><code>{escaped}</code></pre>")
                code_open = False
                code_language = ""
                code_buffer = []
            else:
                close_list()
                flush_table()
                code_open = True
                code_language = line.removeprefix("```").strip()
            continue
        if code_open:
            code_buffer.append(line)
            continue
        if line.startswith("|") and line.endswith("|"):
            close_list()
            table_lines.append(line)
            continue
        flush_table()
        stripped = line.strip()
        if not stripped:
            close_list()
            continue
        if stripped.startswith("# "):
            close_list()
            html_lines.append(f"<h1>{_inline_markdown(stripped[2:])}</h1>")
        elif stripped.startswith("## "):
            close_list()
            html_lines.append(f"<h2>{_inline_markdown(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            close_list()
            html_lines.append(f"<h3>{_inline_markdown(stripped[4:])}</h3>")
        elif stripped.startswith("> "):
            close_list()
            html_lines.append(f"<blockquote><p>{_inline_markdown(stripped[2:])}</p></blockquote>")
        elif stripped.startswith("- "):
            if not list_open:
                html_lines.append("<ul>")
                list_open = True
            html_lines.append(f"<li>{_inline_markdown(stripped[2:])}</li>")
        else:
            close_list()
            html_lines.append(f"<p>{_inline_markdown(stripped)}</p>")

    close_list()
    flush_table()
    return "\n".join(html_lines)


def _render_html_table(lines: list[str]) -> str:
    rows = []
    for line in lines:
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if all(set(cell) <= {"-", " ", ":"} for cell in cells):
            continue
        rows.append(cells)
    if not rows:
        return ""
    header = "".join(f"<th>{_inline_markdown(cell)}</th>" for cell in rows[0])
    body = "\n".join(
        "<tr>" + "".join(f"<td>{_inline_markdown(cell)}</td>" for cell in row) + "</tr>"
        for row in rows[1:]
    )
    return f"<table><thead><tr>{header}</tr></thead><tbody>{body}</tbody></table>"


def _inline_markdown(value: str) -> str:
    escaped = html.escape(value)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
