from __future__ import annotations

import re
import tomllib
from pathlib import Path
from typing import Any

from agentlantern.core.base import BaseRenderer
from agentlantern.frameworks.crewai.analyzer import (
    AgentMethod,
    CrewAIProject,
    TaskMethod,
    _all_tools_in_project,
)


class CrewAIRenderer(BaseRenderer):

    def render_overview(self, project: CrewAIProject) -> str:
        metadata = _pyproject_metadata(project)
        return "\n".join([
            f"# {project.name}",
            "",
            "Generated by [AgentLantern](https://github.com/brellsanwouo/agentlantern) from this CrewAI project.",
            "",
            "## Snapshot",
            "",
            "| Signal | Value |",
            "| --- | --- |",
            "| Framework | `CrewAI` |",
            f"| Process | `{project.process or 'unknown'}` |",
            f"| Agents | `{len(project.agents)}` |",
            f"| Tasks | `{len(project.tasks)}` |",
            f"| Crews detected | `{len(project.crew_methods)}` |",
            f"| Crew class | `{project.crew_class or 'not detected'}` |",
            f"| Kickoff calls detected | `{len(project.kickoff_calls)}` |",
            f"| Tools | `{len(_all_tools(project))}` |",
            f"| Crew file | `{_rel(project, project.crew_path)}` |",
            "",
            "## Contact",
            "",
            "| Name | Email | Source |",
            "| --- | --- | --- |",
            *_contact_rows(metadata),
            "",
            *_metadata_warning_rows(metadata),
            "## Reading Order",
            "",
            "| Order | Page | Role |",
            "| ---: | --- | --- |",
            "| 1 | `overview.md` | Starting point: summary, entrypoints, sharing. |",
            "| 2 | `architecture.md` | What the system does and how it is wired. |",
            "| 3 | `diagrams.md` | Visual maps of agents, tasks, and execution flows. |",
            "| 4 | `agents.md` | Who does what. |",
            "| 5 | `tasks.md` | What work is executed and what output is expected. |",
            "| 6 | `runbook.md` | Installation, execution, and documentation regeneration. |",
            "",
            "## Shareable Version",
            "",
            "| Format | File | Usage |",
            "| --- | --- | --- |",
            "| Docsify Site | `docs/index.html` | Publish the `docs/` folder, e.g. with GitHub Pages. |",
            "| Markdown Bundle | `docs/*.md` | Review or edit the source documentation. |",
            "",
            "## Runtime Entrypoints",
            "",
            "| Function | File | Line |",
            "| --- | --- | ---: |",
            *_kickoff_rows(project),
            "",
            "## High-level Flow",
            "",
            "```mermaid",
            "flowchart LR",
            _render_compact_flow(project),
            "```",
            "",
        ])

    def render_architecture(self, project: CrewAIProject) -> str:
        metadata = _pyproject_metadata(project)
        env_vars = _environment_variables(project)
        lines = [
            "# Architecture",
            "",
            "## Overview",
            "",
            f"CrewAI project `{project.name}`. AgentLantern detected "
            f"class `{project.crew_class or 'unknown'}` (CrewBase), "
            f"`{len(project.crew_methods)}` crew method(s), `{len(project.kickoff_calls)}` kickoff call(s), "
            f"`{len(project.agents)}` agent(s), `{len(project.tasks)}` task(s), process "
            f"`{project.process or 'unknown'}`.",
            "",
            "## Key Files",
            "",
            "| File | Role |",
            "| --- | --- |",
            f"| `{_rel(project, project.crew_path)}` | Crew class, process, agent and task methods. |",
            f"| `{_rel(project, project.agents_config_path)}` | Agent roles, goals, and backstories. |",
            f"| `{_rel(project, project.tasks_config_path)}` | Task descriptions, expected outputs, and assignments. |",
            "",
            "## Runtime Configuration",
            "",
            "| Field | Value |",
            "| --- | --- |",
            f"| Package | `{metadata.get('name', project.name)}` |",
            f"| Version | `{metadata.get('version', 'not declared')}` |",
            f"| Python | `{metadata.get('requires-python', 'not declared')}` |",
            f"| Process | `{project.process or 'unknown'}` |",
            f"| Crew class | `{project.crew_class or 'not detected'}` |",
            f"| Crew methods | `{', '.join(project.crew_methods) or 'not detected'}` |",
            f"| Kickoff calls | `{len(project.kickoff_calls)}` |",
            f"| Contact | `{_contact_summary(metadata)}` |",
            "",
            "## Dependencies",
            "",
        ]
        dependencies = metadata.get("dependencies", [])
        if dependencies:
            lines.extend(f"- `{dep}`" for dep in dependencies)
        else:
            lines.append("No dependencies detected in `pyproject.toml`.")

        lines.extend(["", "## Environment Variables", ""])
        if env_vars:
            lines.extend(["| Variable | Source |", "| --- | --- |"])
            for name, sources in env_vars.items():
                lines.append(f"| `{name}` | {_table_text(', '.join(sorted(sources)))} |")
        else:
            lines.append("No environment variables detected.")

        lines.extend([
            "",
            "## System Map",
            "",
            "```mermaid",
            "flowchart TD",
            _render_mermaid_edges(project),
            "```",
            "",
        ])
        return "\n".join(lines)

    def render_agents(self, project: CrewAIProject) -> str:
        lines = [
            "# Agents",
            "",
            "## Quick Overview",
            "",
            "| Agent | Role | Goal | Tasks | Tools | LLM | Delegation |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for agent_name, agent_config in project.agents.items():
            method = _agent_method_for_config(project, agent_name)
            tools = method.tools if method else []
            tasks = _tasks_for_agent(project, agent_name)
            llm = method.llm if method else None
            delegation = "✓" if (method and method.allow_delegation) else "—"
            lines.append(
                f"| `{agent_name}` | "
                f"{_table_text(_short(agent_config.get('role')))} | "
                f"{_table_text(_short(agent_config.get('goal')))} | "
                f"{_table_code_list(tasks) if tasks else 'none'} | "
                f"{_table_code_list(tools) if tools else 'none'} | "
                f"{_code_or_dash(llm)} | "
                f"{delegation} |"
            )

        lines.extend(["", "## Details", ""])
        for agent_name, agent_config in project.agents.items():
            method = _agent_method_for_config(project, agent_name)
            tools = method.tools if method else []
            flags = []
            if method and method.allow_delegation:
                flags.append("`allow_delegation`")
            if method and method.memory is True:
                flags.append("`memory`")
            lines.extend([
                f"## `{agent_name}`",
                "",
                f"- **Method**: `{method.name if method else 'not found in crew.py'}`",
                f"- **Role**: {_inline(agent_config.get('role'))}",
                f"- **Goal**: {_inline(agent_config.get('goal'))}",
                f"- **Tasks**: {_comma_code(_tasks_for_agent(project, agent_name)) or 'none'}",
                f"- **Tools**: {_comma_code(tools) if tools else 'none detected'}",
                f"- **LLM**: {_code_or_dash(method.llm if method else None)}",
            ])
            if flags:
                lines.append(f"- **Flags**: {', '.join(flags)}")
            lines.append("")
            backstory = _clean(agent_config.get("backstory"))
            if backstory:
                lines.extend(["**Backstory:**", "", backstory, ""])
        return "\n".join(lines)

    def render_tasks(self, project: CrewAIProject) -> str:
        has_context = any(
            m.context_methods for m in project.task_methods.values()
        )
        header = "| Task | Agent | Description | Expected Output |"
        separator = "| --- | --- | --- | --- |"
        if has_context:
            header = "| Task | Agent | Receives context from | Description | Expected Output |"
            separator = "| --- | --- | --- | --- | --- |"

        lines = ["# Tasks", "", "## Quick Overview", "", header, separator]
        for task_name, task_config in project.tasks.items():
            method = _task_method_for_config(project, task_name)
            agent_name = task_config.get("agent") or _agent_from_task_method(project, method)
            ctx = ""
            if has_context:
                ctx_list = method.context_methods if method else []
                ctx = _table_code_list(ctx_list) if ctx_list else "—"

            row = (
                f"| `{task_name}` | "
                f"`{agent_name or 'not declared'}` | "
            )
            if has_context:
                row += f"{ctx} | "
            row += (
                f"{_table_text(_short(task_config.get('description'), limit=80))} | "
                f"{_table_text(_short(task_config.get('expected_output'), limit=80))} |"
            )
            lines.append(row)

        lines.extend(["", "## Details", ""])
        for task_name, task_config in project.tasks.items():
            method = _task_method_for_config(project, task_name)
            agent_name = task_config.get("agent") or _agent_from_task_method(project, method)
            ctx_list = method.context_methods if method else []
            lines.extend([
                f"## `{task_name}`",
                "",
                f"- **Agent**: `{agent_name or 'not declared'}`",
                f"- **Method**: `{method.name if method else 'not found in crew.py'}`",
            ])
            if method and method.output_file:
                lines.append(f"- **Output file**: `{method.output_file}`")
            if ctx_list:
                lines.append(f"- **Receives context from**: {_comma_code(ctx_list)}")
            lines.extend([
                "",
                "**Description:**",
                "",
                _clean(task_config.get("description")) or "No description.",
                "",
                "**Expected Output:**",
                "",
                _clean(task_config.get("expected_output")) or "No expected output declared.",
                "",
            ])
        return "\n".join(lines)

    def render_diagrams(self, project: CrewAIProject) -> str:
        lines = [
            "# Diagrams",
            "",
            "## Agents and Tasks Graph",
            "",
            "```mermaid",
            "flowchart TD",
            _render_mermaid_edges(project),
            "```",
            "",
            "## Execution Flow",
            "",
            "```mermaid",
            "flowchart LR",
            _render_compact_flow(project),
            "```",
            "",
            "## Sequence",
            "",
            "```mermaid",
            "sequenceDiagram",
            "    participant User",
            "    participant Crew",
        ]
        for agent_name in project.agents:
            lines.append(f"    participant {agent_name}")
        lines.extend(_render_sequence_steps(project))
        lines.extend(["```", ""])
        return "\n".join(lines)

    def render_runbook(self, project: CrewAIProject) -> str:
        findings = _quality_findings(project)
        lines = [
            "# Runbook",
            "",
            "## Install",
            "",
            "```bash",
            "crewai install",
            "```",
            "",
            "## Configure",
            "",
            "```bash",
            "cp .env.example .env",
            "$EDITOR .env",
            "```",
            "",
            "## Update Metadata",
            "",
            "CrewAI templates often keep placeholder values. Update `pyproject.toml` before sharing.",
            "",
            "```toml",
            "[project]",
            'authors = [{ name = "Your Name", email = "you@company.com" }]',
            "```",
            "",
            "## Run",
            "",
            "```bash",
            "crewai run",
            "```",
            "",
            "## Regenerate Documentation",
            "",
            "```bash",
            "lantern docs",
            "```",
            "",
            "## View Documentation Locally",
            "",
            "```bash",
            "lantern web",
            "```",
            "",
            "## Share",
            "",
            "Share the full `docs/` folder for the Docsify site, or publish it with GitHub Pages.",
            "",
            "## Static Checks",
            "",
        ]
        if findings:
            lines.extend(["| Severity | Finding |", "| --- | --- |"])
            for severity, message in findings:
                lines.append(f"| `{severity}` | {_table_text(message)} |")
        else:
            lines.append("No static findings detected.")
        lines.extend([
            "",
            "## Troubleshooting",
            "",
            "| Symptom | Fix |",
            "| --- | --- |",
            "| Missing docs | Run `lantern docs` from the CrewAI project root. |",
            "| Agents or tasks absent | Check that `agents.yaml`, `tasks.yaml`, and `crew.py` exist. |",
            "| Crew errors at runtime | Check `.env`, provider credentials, and run `crewai install`. |",
            "| Diagrams not rendering | Open with `lantern web` or a Markdown viewer with Mermaid support. |",
            "",
        ])
        return "\n".join(lines)

    def render_contact(self, project: CrewAIProject) -> str:
        metadata = _pyproject_metadata(project)
        lines = [
            "# Contact",
            "",
            "Contact information extracted from `pyproject.toml`.",
            "",
            "| Name | Email | Source |",
            "| --- | --- | --- |",
            *_contact_rows(metadata),
            "",
        ]
        if _has_placeholder_contact(metadata):
            lines.extend([
                "## CrewAI Metadata to Update",
                "",
                "| Action | File | Why |",
                "| --- | --- | --- |",
                "| Replace placeholder author/contact values | `pyproject.toml` | The CrewAI template still contains `Your Name` / `you@example.com`. |",
                "",
                "Suggested replacement:",
                "",
                "```toml",
                "[project]",
                'authors = [{ name = "Your Name", email = "you@company.com" }]',
                "```",
                "",
            ])
        return "\n".join(lines)


# ── helpers ──────────────────────────────────────────────────────────────────

def _pyproject_metadata(project: CrewAIProject) -> dict[str, Any]:
    pyproject_path = project.root / "pyproject.toml"
    if not pyproject_path.exists():
        return {}
    with pyproject_path.open("rb") as file:
        data = tomllib.load(file)
    result = data.get("project", {})
    return result if isinstance(result, dict) else {}


def _project_contacts(metadata: dict[str, Any]) -> list[dict[str, str]]:
    authors = metadata.get("authors", [])
    contacts = []
    if isinstance(authors, list):
        for author in authors:
            if not isinstance(author, dict):
                continue
            name = str(author.get("name", "")).strip()
            email = str(author.get("email", "")).strip()
            if name or email:
                contacts.append({
                    "name": name or "not declared",
                    "email": email or "not declared",
                })
    return contacts


def _contact_rows(metadata: dict[str, Any]) -> list[str]:
    contacts = _project_contacts(metadata)
    if not contacts:
        return ["| `not declared` | `not declared` | `pyproject.toml` |"]
    return [
        f"| `{_table_text(c['name'])}` | `{_table_text(c['email'])}` | `pyproject.toml` |"
        for c in contacts
    ]


def _contact_summary(metadata: dict[str, Any]) -> str:
    contacts = _project_contacts(metadata)
    if not contacts:
        return "not declared"
    return ", ".join(f"{c['name']} <{c['email']}>" for c in contacts)


def _metadata_warning_rows(metadata: dict[str, Any]) -> list[str]:
    if not _has_placeholder_contact(metadata):
        return []
    return [
        "## CrewAI Metadata to Update",
        "",
        "| Action | File | Why |",
        "| --- | --- | --- |",
        "| Replace placeholder values | `pyproject.toml` | The CrewAI template still contains `Your Name` / `you@example.com`. |",
        "",
    ]


def _has_placeholder_contact(metadata: dict[str, Any]) -> bool:
    for contact in _project_contacts(metadata):
        if contact["name"] == "Your Name" or contact["email"] == "you@example.com":
            return True
    return False


def _environment_variables(project: CrewAIProject) -> dict[str, set[str]]:
    variables: dict[str, set[str]] = {}
    for env_file in [project.root / ".env.example", project.root / ".env"]:
        if not env_file.exists():
            continue
        for line in env_file.read_text(encoding="utf-8").splitlines():
            match = re.match(r"^\s*([A-Z_][A-Z0-9_]*)\s*=", line)
            if match:
                variables.setdefault(match.group(1), set()).add(env_file.name)
    for path in project.package_dir.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        text = path.read_text(encoding="utf-8")
        for pattern in [
            r"os\.getenv\(\s*['\"]([A-Z_][A-Z0-9_]*)['\"]",
            r"os\.environ\[\s*['\"]([A-Z_][A-Z0-9_]*)['\"]\s*\]",
        ]:
            for match in re.finditer(pattern, text):
                variables.setdefault(match.group(1), set()).add(_rel(project, path))
    return dict(sorted(variables.items()))


def _quality_findings(project: CrewAIProject) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    for agent_name in project.agents:
        if not _tasks_for_agent(project, agent_name):
            findings.append(("warning", f"Agent `{agent_name}` is declared but has no assigned task."))
    for task_name, task_config in project.tasks.items():
        if not task_config.get("agent"):
            findings.append(("error", f"Task `{task_name}` has no declared agent."))
        if not _clean(task_config.get("expected_output")):
            findings.append(("warning", f"Task `{task_name}` has no expected output."))
    if not _all_tools(project):
        findings.append(("info", "No tool detected in `crew.py`; this may be normal for a minimal crew."))
    if _has_placeholder_contact(_pyproject_metadata(project)):
        findings.append(("warning", "Project metadata still uses placeholder values in `pyproject.toml`."))
    return findings


def _kickoff_rows(project: CrewAIProject) -> list[str]:
    if not project.kickoff_calls:
        return ["| `not detected` | `not detected` | 0 |"]
    return [
        f"| `{call.function or 'module scope'}` | `{_rel(project, call.file)}` | {call.line} |"
        for call in project.kickoff_calls
    ]


def _all_tools(project: CrewAIProject) -> set[str]:
    return _all_tools_in_project(project)


def _tasks_for_agent(project: CrewAIProject, agent_name: str) -> list[str]:
    return [
        task_name
        for task_name, task_config in project.tasks.items()
        if task_config.get("agent") == agent_name
    ]


def _agent_method_for_config(project: CrewAIProject, agent_name: str) -> AgentMethod | None:
    for method in project.agent_methods.values():
        if method.config_key == agent_name or method.name == agent_name:
            return method
    return None


def _task_method_for_config(project: CrewAIProject, task_name: str) -> TaskMethod | None:
    for method in project.task_methods.values():
        if method.config_key == task_name or method.name == task_name:
            return method
    return None


def _agent_from_task_method(project: CrewAIProject, method: Any) -> str | None:
    if not method or not method.agent_method:
        return None
    agent_method = project.agent_methods.get(method.agent_method)
    return agent_method.config_key if agent_method else method.agent_method


def _render_mermaid_edges(project: CrewAIProject) -> str:
    edges = []
    previous_task = None
    for task_name, task_config in project.tasks.items():
        agent_name = task_config.get("agent", "unknown_agent")
        edges.append(f'    {agent_name}["Agent: {agent_name}"] --> {task_name}["Task: {task_name}"]')
        if previous_task and project.process == "sequential":
            edges.append(f"    {previous_task} --> {task_name}")
        previous_task = task_name
    return "\n".join(edges) if edges else '    empty["No task detected"]'


def _render_compact_flow(project: CrewAIProject) -> str:
    if not project.tasks:
        return '    empty["No task detected"]'
    lines = ['    User["User Input"] --> Crew["Crew kickoff"]']
    previous = "Crew"
    for index, (task_name, task_config) in enumerate(project.tasks.items(), start=1):
        agent_name = task_config.get("agent", "unknown_agent")
        task_node = f"Task{index}"
        agent_node = f"Agent{index}"
        lines.append(f'    {previous} --> {agent_node}["{agent_name}"]')
        lines.append(f'    {agent_node} --> {task_node}["{task_name}"]')
        previous = task_node
    lines.append(f'    {previous} --> Output["Final Output"]')
    return "\n".join(lines)


def _render_sequence_steps(project: CrewAIProject) -> list[str]:
    lines = ["    User->>Crew: kickoff(inputs)"]
    for task_name, task_config in project.tasks.items():
        agent_name = task_config.get("agent", "Crew")
        lines.append(f"    Crew->>{agent_name}: assign {task_name}")
        lines.append(f"    {agent_name}-->>Crew: return task result")
    lines.append("    Crew-->>User: final output")
    return lines


def _rel(project: CrewAIProject, path: Path) -> str:
    return str(path.relative_to(project.root))


def _clean(value: Any) -> str:
    if value is None:
        return ""
    return " ".join(str(value).split())


def _inline(value: Any) -> str:
    cleaned = _clean(value)
    return cleaned if cleaned else "not provided"


def _short(value: Any, limit: int = 96) -> str:
    cleaned = _clean(value)
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[: limit - 1].rstrip() + "..."


def _table_text(value: Any) -> str:
    cleaned = _clean(value)
    return cleaned.replace("|", "\\|") if cleaned else "not provided"


def _comma_code(values: list[str] | set[str]) -> str:
    return ", ".join(f"`{v}`" for v in values)


def _table_code_list(values: list[str]) -> str:
    return "<br>".join(f"`{v}`" for v in values)


def _code_or_dash(value: str | None) -> str:
    return f"`{value}`" if value else "—"
