from __future__ import annotations

from pathlib import Path
from typing import Any

from agentlantern.core.base import BaseRenderer
from agentlantern.frameworks.google_adk.analyzer import (
    ADKAgentInfo,
    ADKToolInfo,
    GoogleADKProject,
)


class GoogleADKRenderer(BaseRenderer):

    def render_overview(self, project: GoogleADKProject) -> str:
        meta = project.package_metadata
        lines = [
            f"# {project.name}",
            "",
            "Generated by [AgentLantern](https://github.com/brellsanwouo/agentlantern) from this Google ADK project.",
            "",
            "## Snapshot",
            "",
            "| Signal | Value |",
            "| --- | --- |",
            "| Framework | `Google ADK` |",
            f"| Agents | `{len(project.agents)}` |",
            f"| Tools | `{len(project.tools)}` |",
            f"| Pydantic Models | `{len(project.pydantic_models)}` |",
            f"| CLI Entrypoints | `{len(project.entry_points)}` |",
            f"| Version | `{meta.get('version', 'not declared')}` |",
            f"| Python | `{meta.get('requires-python', 'not declared')}` |",
        ]
        if project.llm_providers:
            lines.append(f"| LLM Providers detected | {_comma_code(project.llm_providers)} |")

        lines.extend(["", "## Contact", "", "| Name | Email | Source |", "| --- | --- | --- |"])
        lines.extend(_contact_rows(meta))

        lines.extend(["", "## Agents", ""])
        if project.agents:
            lines.extend([
                "| Agent | ADK Name | Description | Sub-agents | Tools |",
                "| --- | --- | --- | --- | --- |",
            ])
            for agent in project.agents:
                lines.append(
                    f"| `{agent.class_name}` | "
                    f"{_code_or_dash(agent.adk_name)} | "
                    f"{_table_text(_short(agent.description))} | "
                    f"{_table_code_list(agent.sub_agents) if agent.sub_agents else '—'} | "
                    f"{_table_code_list(agent.tools) if agent.tools else '—'} |"
                )
        else:
            lines.append("No Google ADK agent detected.")

        lines.extend(["", "## CLI Entrypoints", ""])
        if project.entry_points:
            lines.extend(["| Command | Target |", "| --- | --- |"])
            for ep in project.entry_points:
                lines.append(f"| `{ep.command}` | `{ep.target}` |")
        else:
            lines.append("No entrypoint declared in `pyproject.toml`.")

        if project.cli_commands:
            lines.extend(["", "## Available CLI Commands", ""])
            lines.extend(["| Command | Description |", "| --- | --- |"])
            for cmd in project.cli_commands:
                lines.append(f"| `{cmd.name}` | {_table_text(cmd.description)} |")

        lines.extend(["", "## High-level Flow", "", "```mermaid", "flowchart LR"])
        lines.append(_render_top_level_flow(project))
        lines.extend(["```", ""])
        return "\n".join(lines)

    def render_architecture(self, project: GoogleADKProject) -> str:
        meta = project.package_metadata
        lines = [
            "# Architecture",
            "",
            "## Overview",
            "",
            f"**Google ADK** project `{project.name}`. "
            f"AgentLantern detected `{len(project.agents)}` agent(s), "
            f"`{len(project.tools)}` tool(s), and "
            f"`{len(project.pydantic_models)}` Pydantic model(s).",
            "",
            "## Runtime Configuration",
            "",
            "| Field | Value |",
            "| --- | --- |",
            f"| Package | `{meta.get('name', project.name)}` |",
            f"| Version | `{meta.get('version', 'not declared')}` |",
            f"| Python | `{meta.get('requires-python', 'not declared')}` |",
            f"| Agents | `{len(project.agents)}` |",
            f"| Tools | `{len(project.tools)}` |",
        ]
        if project.llm_providers:
            lines.append(f"| LLM Providers | {_comma_code(project.llm_providers)} |")

        deps = meta.get("dependencies", [])
        lines.extend(["", "## Dependencies", ""])
        if deps:
            lines.extend(f"- `{d}`" for d in deps)
        else:
            lines.append("No dependencies declared in `pyproject.toml`.")

        lines.extend(["", "## Environment Variables", ""])
        if project.env_vars:
            lines.extend(["| Variable | Source |", "| --- | --- |"])
            for name, sources in project.env_vars.items():
                lines.append(f"| `{name}` | {_table_text(', '.join(sorted(sources)))} |")
        else:
            lines.append("No environment variables detected.")

        lines.extend(["", "## Agent Hierarchy", "", "```mermaid", "flowchart TD"])
        lines.append(_render_agent_hierarchy(project))
        lines.extend(["```", ""])

        if project.pydantic_models:
            lines.extend(["## Data Models (Pydantic)", ""])
            lines.append(_comma_code(project.pydantic_models))
            lines.append("")

        return "\n".join(lines)

    def render_agents(self, project: GoogleADKProject) -> str:
        if not project.agents:
            return "# Agents\n\nNo Google ADK agent detected in this project.\n"

        lines = [
            "# Agents",
            "",
            "## Quick Overview",
            "",
            "| Agent | ADK Name | Description | Base | Tools | Sub-agents |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for agent in project.agents:
            lines.append(
                f"| `{agent.class_name}` | "
                f"{_code_or_dash(agent.adk_name)} | "
                f"{_table_text(_short(agent.description))} | "
                f"{_table_code_list(agent.base_classes)} | "
                f"{_table_code_list(agent.tools) if agent.tools else '—'} | "
                f"{_table_code_list(agent.sub_agents) if agent.sub_agents else '—'} |"
            )

        lines.extend(["", "## Details", ""])
        for agent in project.agents:
            lines.extend([
                f"## `{agent.class_name}`",
                "",
                f"- **ADK Name**: {_inline_code_or(agent.adk_name, 'not declared')}",
                f"- **File**: `{agent.file.name}` (line {agent.line})",
                f"- **Inherits from**: {_comma_code(agent.base_classes)}",
            ])
            if agent.description:
                lines.extend(["", agent.description, ""])
            if agent.tools:
                lines.extend([
                    "",
                    f"**Tools**: {_comma_code(agent.tools)}",
                ])
            if agent.sub_agents:
                lines.extend([
                    "",
                    f"**Sub-agents instantiated**: {_comma_code(agent.sub_agents)}",
                ])
            lines.append("")
        return "\n".join(lines)

    def render_tasks(self, project: GoogleADKProject) -> str:
        """Satisfies the abstract requirement; actual output lives in render_workflows()."""
        return self.render_workflows(project)

    def render_workflows(self, project: GoogleADKProject) -> str:
        lines = [
            "# Workflows",
            "",
            "> Agent execution pipeline — from CLI input to leaf agents.",
            "",
        ]

        if project.agents:
            orchestrators = [a for a in project.agents if a.sub_agents]
            leaf_agents = [a for a in project.agents if not a.sub_agents]

            if orchestrators:
                lines.extend(["## Orchestrator Agents", ""])
                for agent in orchestrators:
                    lines.append(
                        f"- `{agent.adk_name or agent.class_name}` → "
                        f"delegates to: {_comma_code(agent.sub_agents)}"
                    )
                lines.append("")

            if leaf_agents:
                lines.extend(["## Leaf Agents (direct execution)", ""])
                for agent in leaf_agents:
                    tool_str = f" — tools: {_comma_code(agent.tools)}" if agent.tools else ""
                    lines.append(f"- `{agent.adk_name or agent.class_name}`{tool_str}")
                lines.append("")

            lines.extend([
                "## Full Pipeline",
                "",
                "```mermaid",
                "flowchart TD",
                _render_agent_hierarchy(project),
                "```",
                "",
            ])

        if project.cli_commands:
            lines.extend([
                "## CLI Commands",
                "",
                "| Command | Description | File |",
                "| --- | --- | --- |",
            ])
            for cmd in project.cli_commands:
                lines.append(
                    f"| `{cmd.name}` | "
                    f"{_table_text(cmd.description)} | "
                    f"`{cmd.file.name}` |"
                )
            lines.append("")

        if project.entry_points:
            lines.extend([
                "## Entrypoints (`pyproject.toml`)",
                "",
                "| Shell command | Target module |",
                "| --- | --- |",
            ])
            for ep in project.entry_points:
                lines.append(f"| `{ep.command}` | `{ep.target}` |")
            lines.append("")

        return "\n".join(lines)

    def render_tools(self, project: GoogleADKProject) -> str:
        lines = [
            "# Tools",
            "",
            "Reference for all tools available in this Google ADK project.",
            "",
        ]

        if not project.tools:
            lines.append("No Google ADK tool detected in this project.\n")
            return "\n".join(lines)

        decorated = [t for t in project.tools if t.is_adk_decorated]
        by_dir = [t for t in project.tools if not t.is_adk_decorated]

        lines.extend([
            "## Quick Overview",
            "",
            "| Tool | Description | Parameters | ADK Decorator | File |",
            "| --- | --- | --- | --- | --- |",
        ])
        for tool in project.tools:
            params = ", ".join(f"`{p}`" for p in tool.parameters) if tool.parameters else "—"
            lines.append(
                f"| `{tool.name}` | "
                f"{_table_text(_short(tool.description))} | "
                f"{params} | "
                f"{'✓' if tool.is_adk_decorated else '—'} | "
                f"`{tool.file.name}` |"
            )
        lines.append("")

        if decorated:
            lines.extend(["## Tools decorated with `@tool`", ""])
            for tool in decorated:
                lines.extend([
                    f"### `{tool.name}`",
                    "",
                    f"- **File**: `{tool.file.name}` (line {tool.line})",
                ])
                if tool.parameters:
                    lines.append(f"- **Parameters**: {', '.join(f'`{p}`' for p in tool.parameters)}")
                if tool.description:
                    lines.extend(["", tool.description])
                lines.append("")

        if by_dir:
            lines.extend(["## Tools in `tools/`", ""])
            for tool in by_dir:
                lines.extend([
                    f"### `{tool.name}`",
                    "",
                    f"- **File**: `{tool.file.name}` (line {tool.line})",
                ])
                if tool.parameters:
                    lines.append(f"- **Parameters**: {', '.join(f'`{p}`' for p in tool.parameters)}")
                if tool.description:
                    lines.extend(["", tool.description])
                lines.append("")

        agents_with_tools = [a for a in project.agents if a.tools]
        if agents_with_tools:
            lines.extend(["## Usage by Agents", ""])
            for agent in agents_with_tools:
                lines.append(
                    f"- `{agent.adk_name or agent.class_name}`: {_comma_code(agent.tools)}"
                )
            lines.append("")

        return "\n".join(lines)

    def render_diagrams(self, project: GoogleADKProject) -> str:
        lines = [
            "# Diagrams",
            "",
            "## Agent Hierarchy",
            "",
            "```mermaid",
            "flowchart TD",
            _render_agent_hierarchy(project),
            "```",
            "",
            "## Execution Flow",
            "",
            "```mermaid",
            "flowchart LR",
            _render_top_level_flow(project),
            "```",
        ]

        agents_with_tools = [a for a in project.agents if a.tools]
        if agents_with_tools:
            lines.extend([
                "",
                "## Agent — Tools Graph",
                "",
                "```mermaid",
                "flowchart LR",
            ])
            for agent in agents_with_tools:
                name = agent.adk_name or agent.class_name
                for tool in agent.tools:
                    lines.append(f'    {_mermaid_id(name)}["{name}"] --> {_mermaid_id(tool)}("{tool}")')
            lines.extend(["```", ""])

        if project.entry_points and project.agents:
            lines.extend([
                "## CLI → Agents Sequence",
                "",
                "```mermaid",
                "sequenceDiagram",
                "    participant User",
                "    participant CLI",
            ])
            for agent in project.agents:
                lines.append(f"    participant {_mermaid_id(agent.adk_name or agent.class_name)}")
            lines.append("    User->>CLI: command (e.g. assess / parse)")
            lines.append("    CLI->>CLI: load .env, create LLMClient")
            for agent in project.agents:
                aname = agent.adk_name or agent.class_name
                lines.append(f"    CLI->>{_mermaid_id(aname)}: instantiate and run")
                if agent.sub_agents:
                    for sub in agent.sub_agents:
                        lines.append(f"    {_mermaid_id(aname)}->>{_mermaid_id(sub)}: delegate")
                        lines.append(f"    {_mermaid_id(sub)}-->>{_mermaid_id(aname)}: result")
                lines.append(f"    {_mermaid_id(aname)}-->>CLI: result")
            lines.append("    CLI-->>User: output (JSON / TXT)")
            lines.extend(["```", ""])

        return "\n".join(lines)

    def render_runbook(self, project: GoogleADKProject) -> str:
        meta = project.package_metadata
        pkg_name = meta.get("name", project.name)
        lines = [
            "# Runbook",
            "",
            "## Install",
            "",
            "```bash",
            f"pip install {pkg_name}",
            "# or",
            f"uv pip install {pkg_name}",
            "```",
            "",
            "## Configure",
            "",
            "```bash",
            "cp .env.example .env",
            "$EDITOR .env",
            "```",
            "",
        ]

        if project.env_vars:
            lines.extend(["Environment variables to configure:", ""])
            lines.extend(["| Variable | Source |", "| --- | --- |"])
            for name, sources in list(project.env_vars.items())[:15]:
                lines.append(f"| `{name}` | `{', '.join(sorted(sources))}` |")
            lines.append("")

        lines.extend(["## Run", ""])
        if project.entry_points:
            for ep in project.entry_points:
                lines.extend([f"```bash", f"{ep.command} --help", "```", ""])
        if project.cli_commands:
            lines.extend([
                "### Available Commands",
                "",
                "| Command | Description |",
                "| --- | --- |",
            ])
            for cmd in project.cli_commands:
                lines.append(f"| `{cmd.name}` | {_table_text(cmd.description)} |")
            lines.append("")

        lines.extend([
            "## Regenerate Documentation",
            "",
            "```bash",
            f"lantern docs /path/to/{project.name}",
            "```",
            "",
            "## View Documentation Locally",
            "",
            "```bash",
            f"lantern web /path/to/{project.name}",
            "```",
            "",
            "## Troubleshooting",
            "",
            "| Symptom | Fix |",
            "| --- | --- |",
            "| `LLMError` or `AuthenticationError` | Check `OPENAI_API_KEY` in `.env`. |",
            "| Agents not detected | Check that classes inherit from `BaseAgent` or an ADK subclass. |",
            "| Diagrams not rendering | Open with `lantern web` (Mermaid requires a browser). |",
            "",
        ])
        return "\n".join(lines)

    def render_contact(self, project: GoogleADKProject) -> str:
        meta = project.package_metadata
        lines = [
            "# Contact",
            "",
            "Contact information extracted from `pyproject.toml`.",
            "",
            "| Name | Email | Source |",
            "| --- | --- | --- |",
            *_contact_rows(meta),
            "",
        ]
        return "\n".join(lines)

    def get_doc_structure(self, project: GoogleADKProject) -> list[tuple[str, str]]:  # type: ignore[override]
        return [
            ("overview.md",      self.render_overview(project)),
            ("architecture.md",  self.render_architecture(project)),
            ("diagrams.md",      self.render_diagrams(project)),
            ("agents.md",        self.render_agents(project)),
            ("tools.md",         self.render_tools(project)),
            ("workflows.md",     self.render_workflows(project)),
            ("runbook.md",       self.render_runbook(project)),
            ("contact.md",       self.render_contact(project)),
        ]


# ── Diagram helpers ────────────────────────────────────────────────────────────

def _render_agent_hierarchy(project: GoogleADKProject) -> str:
    if not project.agents:
        return '    empty["No agent detected"]'
    lines = []
    seen: set[str] = set()
    for agent in project.agents:
        aname = agent.adk_name or agent.class_name
        aid = _mermaid_id(aname)
        if aid not in seen:
            lines.append(f'    {aid}["{aname}"]')
            seen.add(aid)
        for base in agent.base_classes:
            bid = _mermaid_id(base)
            if bid not in seen:
                lines.append(f'    {bid}(("{base}"))')
                seen.add(bid)
            lines.append(f"    {bid} --> {aid}")
        for sub in agent.sub_agents:
            sid = _mermaid_id(sub)
            if sid not in seen:
                lines.append(f'    {sid}["{sub}"]')
                seen.add(sid)
            lines.append(f"    {aid} --> {sid}")
    return "\n".join(lines) if lines else '    empty["No agent detected"]'


def _render_top_level_flow(project: GoogleADKProject) -> str:
    lines = ['    User["User"] --> CLI["CLI / UI"]']
    if not project.agents:
        lines.append('    CLI --> empty["No agent detected"]')
        return "\n".join(lines)
    orchestrators = [a for a in project.agents if a.sub_agents]
    leaves = [a for a in project.agents if not a.sub_agents]
    shown: set[str] = set()
    for agent in orchestrators:
        aname = agent.adk_name or agent.class_name
        aid = _mermaid_id(aname)
        if aid not in shown:
            lines.append(f'    CLI --> {aid}["{aname}"]')
            shown.add(aid)
        for sub in agent.sub_agents:
            sid = _mermaid_id(sub)
            if sid not in shown:
                lines.append(f'    {aid} --> {sid}["{sub}"]')
                shown.add(sid)
    for agent in leaves:
        aname = agent.adk_name or agent.class_name
        aid = _mermaid_id(aname)
        if aid not in shown:
            lines.append(f'    CLI --> {aid}["{aname}"]')
            shown.add(aid)
    lines.append('    CLI --> Output["Output (JSON / report)"]')
    return "\n".join(lines)


def _mermaid_id(name: str) -> str:
    import re
    return re.sub(r"[^a-zA-Z0-9]", "_", name)


# ── Text helpers ───────────────────────────────────────────────────────────────

def _contact_rows(meta: dict) -> list[str]:
    authors = meta.get("authors", [])
    rows = []
    if isinstance(authors, list):
        for a in authors:
            if not isinstance(a, dict):
                continue
            name = str(a.get("name", "")).strip() or "not declared"
            email = str(a.get("email", "")).strip() or "not declared"
            rows.append(f"| `{name}` | `{email}` | `pyproject.toml` |")
    return rows or ["| `not declared` | `not declared` | `pyproject.toml` |"]


def _clean(value: Any) -> str:
    if value is None:
        return ""
    return " ".join(str(value).split())


def _short(value: Any, limit: int = 96) -> str:
    cleaned = _clean(value)
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[:limit - 1].rstrip() + "..."


def _table_text(value: Any) -> str:
    cleaned = _clean(value)
    return cleaned.replace("|", "\\|") if cleaned else "—"


def _comma_code(values: list[str] | set[str]) -> str:
    return ", ".join(f"`{v}`" for v in values)


def _table_code_list(values: list[str]) -> str:
    return "<br>".join(f"`{v}`" for v in values)


def _code_or_dash(value: str | None) -> str:
    return f"`{value}`" if value else "—"


def _inline_code_or(value: str | None, fallback: str) -> str:
    return f"`{value}`" if value else fallback
